import type { Locale } from "../../../lib/i18n";

const zh = {
  entry: "助手",
  newAssistant: "新建助手",
  loading: "正在唤醒助手…",
  loadFailed: "助手状态读取失败",
  retry: "重新读取",
  emptyTitle: "给长期工作一个持续醒着的助手",
  emptyBody: "它会按自己的频率工作，把明确记忆和每次运行结果留在这里。",
  awake: "醒着",
  paused: "已暂停",
  archived: "已归档",
  continueWork: "让它继续工作",
  queued: "已记录并排队，助手会在后台处理。",
  inputRecorded: "输入会被记录",
  youSaid: "你对助手说",
  manage: "管理助手",
  close: "关闭",
  today: "今天",
  timelineEmpty: "今天还没有运行记录。你可以先交代一件事，或让它继续工作。",
  learned: "我记住了",
  next: "接下来",
  changeTime: "改成别的时间",
  taskPlaceholder: "对助手说…",
  send: "发送",
  sendShortcut: "发送",
  overview: "概览",
  routines: "例行任务",
  memory: "显式记忆",
  history: "运行记录",
  attention: "待处理",
  name: "名称",
  mission: "长期使命",
  workspace: "工作区",
  scope: "作用范围",
  scopeGlobal: "全局",
  scopeWorkspace: "项目工作区",
  workspaceFreezeHint: "已经排队的运行保留创建时的工作区；保存后，新运行才使用新的路径。",
  partialWarning: "部分助手数据无法读取，健康助手仍可正常使用。",
  viewDetails: "查看详情",
  diagnosticTitle: "读取诊断",
  save: "保存",
  pause: "暂停",
  resume: "唤醒",
  deleteAssistant: "删除助手",
  deleteAssistantTitle: "删除这个助手",
  deleteAssistantBody: "助手配置、计划、记忆和运行记录会从助手模式移除；它创建过的 Session 仍保留在最近列表中。",
  confirmDeleteAssistant: "确认删除",
  deletedAssistant: "助手已删除",
  routineTitle: "例行任务名称",
  routinePrompt: "每次运行要做什么",
  frequency: "运行频率",
  manual: "仅手动",
  interval: "固定间隔",
  daily: "每天",
  weekly: "每周",
  hour: "小时",
  at: "时间",
  timezone: "时区",
  runNow: "立即运行",
  enabled: "启用",
  memoryKind: "记忆类型",
  memoryBody: "它应该明确记住什么",
  addMemory: "写入记忆",
  charter: "使命约束",
  facts: "事实",
  strategy: "策略",
  openLoops: "开放事项",
  metrics: "指标",
  noMemory: "还没有显式记忆。助手不会把猜测当成事实。",
  noHistory: "还没有运行记录。",
  noAttention: "没有需要你处理的事项。",
  approve: "批准",
  continueRun: "继续运行",
  reject: "拒绝",
  answer: "回答",
  answerPlaceholder: "输入给助手的明确回答…",
  confirmRetry: "确认重试",
  markSucceeded: "标记成功",
  markFailed: "标记失败",
  cancel: "取消",
  retryRun: "重试",
  rerun: "重新运行",
  waitingRetry: "系统会按计划自动重试，也可以取消这次运行。",
  handleAttention: "去处理",
  changeProject: "修改项目",
  cancelOldRun: "取消旧运行",
  rebindWarning: "这次运行已冻结旧项目路径。请先保存新路径，再重新运行；批准旧运行仍会使用旧路径。",
  stopRun: "停止",
  openSession: "打开会话",
  createTitle: "创建一个长期助手",
  createBody: "先给它一个清楚的使命，再决定多久醒来一次。",
  create: "创建助手",
  createName: "例如：代码项目助手",
  createMission: "例如：持续关注项目健康度，在发布条件满足时询问我。",
  workspacePick: "选择",
  workspaceNew: "新建",
  workspaceNewParent: "父目录",
  workspaceNewName: "目录名",
  workspaceNewNamePlaceholder: "例如：my-project",
  workspaceNewCreate: "创建",
  error: "操作失败，请重试。",
  saved: "已保存",
  resolveNote: "由桌面端处理",
  rejectNote: "用户拒绝回答",
  templates: "选择模板",
  templateCode: "代码项目",
  templateGeneral: "通用",
  templatePromo: "推广",
  templateCodeDesc: "项目健康检查、测试/构建、发布准备，发布前必须审批。",
  templateGeneralDesc: "使命与例行任务由你填写，默认只读。",
  templatePromoDesc: "外部渠道连接与效果采集属于阶段 4 能力。",
  phase4Preview: "阶段 4 预告",
  routinePreview: "将创建以下例行任务",
  permissionTitle: "权限摘要",
  permissionConfirm: "我已了解并确认以上权限设置",
  learnFirst: "先学习一下再干",
  learnFirstHint: "作为第一个任务：联网搜索类似任务好用的 Skill，评估后安装安全的项目级 Skill，并记录学习结果。选择后会自动允许网络和本地写入。",
  learnFirstPrompt: "先学习一下再干",
  policyLocalWrite: "本地写入",
  policyNetwork: "网络",
  policyPublish: "对外发布",
  policyDelete: "删除",
  policyPayment: "付费",
  policySecrets: "凭据",
  policyPrivateData: "私有数据",
  policyHighRisk: "删除 / 付费 / 凭据",
  policyAskNote: "发布、删除、付费、凭据与私有数据始终逐次审批；“允许”不会绕过人工确认。",
  policyFreezeHint: "排队中和运行中的运行保留旧权限快照；保存后，仅新运行使用新权限。",
  accessAllow: "自动允许",
  accessAllowAsk: "允许（仍逐次审批）",
  accessDeny: "拒绝",
  accessApprove: "逐次审批",
  routineFrequencyManual: "仅手动",
  noRoutines: "还没有例行任务。",
  addRoutine: "新增例行任务",
  plan: "计划",
  planEmpty: "还没有责任。助手会在推进使命时，把责任、依赖和证据记在这里。",
  responsibility: "责任",
  status: "状态",
  doneCriteria: "完成标准",
  nextAction: "下一步",
  dependsOn: "依赖",
  blockReason: "阻塞原因",
  artifacts: "证据与产物",
  opportunities: "机会与提案",
  noArtifacts: "还没有证据或产物。",
  noOpportunities: "还没有机会或提案。",
};

const en: typeof zh = {
  entry: "Assistants", newAssistant: "New assistant", loading: "Waking the assistant…", loadFailed: "Couldn't load assistants", retry: "Try again",
  emptyTitle: "Give ongoing work an assistant that stays with it", emptyBody: "It runs on its own rhythm and keeps explicit memory and an auditable history.",
  awake: "Awake", paused: "Paused", archived: "Archived", continueWork: "Let it continue", queued: "Recorded and queued. The assistant will handle it in the background.", inputRecorded: "Your input is recorded", youSaid: "You told the assistant",
  manage: "Manage assistant", close: "Close", today: "Today", timelineEmpty: "No runs today. Hand off a task or let it continue.", learned: "I remembered", next: "Next",
  changeTime: "Change time", taskPlaceholder: "Talk to the assistant…", send: "Send", sendShortcut: "Send", overview: "Overview", routines: "Routines", memory: "Explicit memory",
  history: "Run history", attention: "Attention", name: "Name", mission: "Long-term mission", workspace: "Workspace", scope: "Scope", scopeGlobal: "Global", scopeWorkspace: "Project workspace", save: "Save", pause: "Pause", resume: "Wake",
  deleteAssistant: "Delete assistant", deleteAssistantTitle: "Delete this assistant", deleteAssistantBody: "Its configuration, plan, memory, and run history will leave Assistant mode. Sessions it created stay in Recent.", confirmDeleteAssistant: "Delete", deletedAssistant: "Assistant deleted",
  workspaceFreezeHint: "Queued runs keep their frozen workspace. New runs use the updated path after saving.", partialWarning: "Some assistant data couldn't be read. Healthy assistants are still available.", viewDetails: "View details", diagnosticTitle: "Read diagnostics",
  routineTitle: "Routine name", routinePrompt: "What to do on each run", frequency: "Run frequency", manual: "Manual only", interval: "Fixed interval", daily: "Daily",
  weekly: "Weekly", hour: "hours", at: "Time", timezone: "Timezone", runNow: "Run now", enabled: "Enabled", memoryKind: "Memory type",
  memoryBody: "What should it remember explicitly?", addMemory: "Add memory", charter: "Charter", facts: "Facts", strategy: "Strategy", openLoops: "Open loops", metrics: "Metrics",
  noMemory: "No explicit memory yet. The assistant won't treat guesses as facts.", noHistory: "No run history yet.", noAttention: "Nothing needs your attention.",
  approve: "Approve", continueRun: "Continue run", reject: "Reject", answer: "Answer", answerPlaceholder: "Enter a clear answer for the assistant…", confirmRetry: "Confirm retry", markSucceeded: "Mark succeeded", markFailed: "Mark failed", cancel: "Cancel", retryRun: "Retry", rerun: "Run again", waitingRetry: "The system will retry on schedule, or you can cancel this run.", handleAttention: "Review", changeProject: "Change project", cancelOldRun: "Cancel old run", rebindWarning: "This run froze the previous project path. Save the new path, then run again; approving this run would still use the old path.", stopRun: "Stop", openSession: "Open session", createTitle: "Create an ongoing assistant",
  createBody: "Give it a clear mission, then choose how often it should wake up.", create: "Create assistant", createName: "e.g. Code project assistant",
  createMission: "e.g. Track project health and ask before publishing when ready.",
  workspacePick: "Choose",
  workspaceNew: "New",
  workspaceNewParent: "Parent folder",
  workspaceNewName: "Folder name",
  workspaceNewNamePlaceholder: "e.g. my-project",
  workspaceNewCreate: "Create",
  error: "That didn't work. Please retry.", saved: "Saved", resolveNote: "Resolved from Desktop", rejectNote: "The user declined to answer", templates: "Choose a template", templateCode: "Code project", templateGeneral: "General", templatePromo: "Promotion",
  templateCodeDesc: "Project health, test/build, release readiness; publishing always asks first.", templateGeneralDesc: "Mission and routines are yours to fill; read-only by default.",
  templatePromoDesc: "External channels and effect collection are a phase-4 capability.", phase4Preview: "Phase 4 preview", routinePreview: "It will create these routines",
  permissionTitle: "Permissions", permissionConfirm: "I understand and confirm these permissions",
  learnFirst: "Learn before working",
  learnFirstHint: "Make this the first task: search online for useful Skills for similar work, evaluate them, safely install a project Skill, and record the result. This enables network and local writes.",
  learnFirstPrompt: "Learn before working",
  policyLocalWrite: "Local writes", policyNetwork: "Network", policyPublish: "Publishing",
  policyDelete: "Delete", policyPayment: "Payment", policySecrets: "Credentials", policyPrivateData: "Private data",
  policyHighRisk: "Delete / payment / credentials",
  policyAskNote: "Publishing, delete, payment, credentials, and private data always ask per action — “Allow” never skips manual approval.",
  policyFreezeHint: "Queued and running runs keep their frozen permission snapshot. Only new runs use the updated policy after saving.",
  accessAllow: "Auto-allow", accessAllowAsk: "Allow (still asks)", accessDeny: "Deny", accessApprove: "Per-action approval", routineFrequencyManual: "Manual only",
  noRoutines: "No routines yet.", addRoutine: "Add routine",
  plan: "Plan", planEmpty: "No responsibilities yet. The assistant records responsibilities, dependencies, and evidence here as it works its mission.",
  responsibility: "Responsibility", status: "Status", doneCriteria: "Done criteria", nextAction: "Next action", dependsOn: "Depends on", blockReason: "Blocked reason",
  artifacts: "Artifacts & evidence", opportunities: "Opportunities & proposals", noArtifacts: "No artifacts or evidence yet.", noOpportunities: "No opportunities or proposals yet.",
};

const zhTW: typeof zh = { ...zh, entry: "助手", newAssistant: "新增助手", memory: "明確記憶", history: "執行記錄", attention: "待處理", save: "儲存", sendShortcut: "傳送", workspacePick: "選擇", workspaceNew: "新增", workspaceNewParent: "父資料夾", workspaceNewName: "資料夾名稱", workspaceNewNamePlaceholder: "例如：my-project", workspaceNewCreate: "建立" };

export type AssistantCopy = typeof zh;

export function assistantCopy(locale: Locale): AssistantCopy {
  if (locale === "en") return en;
  if (locale === "zh-TW") return zhTW;
  return zh;
}
