import type { Locale } from "../../../lib/i18n";

const zh = {
  entry: "助理",
  newAssistant: "新建助理",
  loading: "正在唤醒助理…",
  loadFailed: "助理状态读取失败",
  retry: "重新读取",
  emptyTitle: "给长期工作一个持续醒着的助理",
  emptyBody: "它会按自己的频率工作，把明确记忆和每次运行结果留在这里。",
  awake: "醒着",
  paused: "已暂停",
  archived: "已归档",
  continueWork: "让它继续工作",
  queued: "已经交给助理，它会在后台继续。",
  manage: "管理助理",
  close: "关闭",
  today: "今天",
  timelineEmpty: "今天还没有运行记录。你可以先交代一件事，或让它继续工作。",
  learned: "我记住了",
  next: "接下来",
  changeTime: "改成别的时间",
  taskPlaceholder: "交代给它一件事…",
  send: "交代",
  overview: "概览",
  routines: "例行任务",
  memory: "显式记忆",
  history: "运行记录",
  attention: "待处理",
  name: "名称",
  mission: "长期使命",
  workspace: "工作区",
  scope: "作用范围",
  scopeGlobal: "全局",
  scopeWorkspace: "项目工作区",
  workspaceFreezeHint: "已经排队的运行保留创建时的工作区；保存后，新运行才使用新的路径。",
  partialWarning: "部分助理数据无法读取，健康助理仍可正常使用。",
  viewDetails: "查看详情",
  diagnosticTitle: "读取诊断",
  save: "保存",
  pause: "暂停",
  resume: "唤醒",
  routineTitle: "例行任务名称",
  routinePrompt: "每次运行要做什么",
  frequency: "运行频率",
  manual: "仅手动",
  interval: "固定间隔",
  daily: "每天",
  weekly: "每周",
  hour: "小时",
  at: "时间",
  timezone: "时区",
  runNow: "立即运行",
  enabled: "启用",
  memoryKind: "记忆类型",
  memoryBody: "它应该明确记住什么",
  addMemory: "写入记忆",
  charter: "使命约束",
  facts: "事实",
  strategy: "策略",
  openLoops: "开放事项",
  metrics: "指标",
  noMemory: "还没有显式记忆。助理不会把猜测当成事实。",
  noHistory: "还没有运行记录。",
  noAttention: "没有需要你处理的事项。",
  approve: "批准",
  continueRun: "继续运行",
  reject: "拒绝",
  answer: "回答",
  answerPlaceholder: "输入给助理的明确回答…",
  confirmRetry: "确认重试",
  markSucceeded: "标记成功",
  markFailed: "标记失败",
  cancel: "取消",
  retryRun: "重试",
  rerun: "重新运行",
  waitingRetry: "系统会按计划自动重试，也可以取消这次运行。",
  handleAttention: "去处理",
  changeProject: "修改项目",
  cancelOldRun: "取消旧运行",
  rebindWarning: "这次运行已冻结旧项目路径。请先保存新路径，再重新运行；批准旧运行仍会使用旧路径。",
  stopRun: "停止",
  openSession: "打开会话",
  createTitle: "创建一个长期助理",
  createBody: "先给它一个清楚的使命，再决定多久醒来一次。",
  create: "创建助理",
  createName: "例如：代码项目助理",
  createMission: "例如：持续关注项目健康度，在发布条件满足时询问我。",
  error: "操作失败，请重试。",
  saved: "已保存",
  resolveNote: "由桌面端处理",
  rejectNote: "用户拒绝回答",
};

const en: typeof zh = {
  entry: "Assistants", newAssistant: "New assistant", loading: "Waking the assistant…", loadFailed: "Couldn't load assistants", retry: "Try again",
  emptyTitle: "Give ongoing work an assistant that stays with it", emptyBody: "It runs on its own rhythm and keeps explicit memory and an auditable history.",
  awake: "Awake", paused: "Paused", archived: "Archived", continueWork: "Let it continue", queued: "Handed off. The assistant will continue in the background.",
  manage: "Manage assistant", close: "Close", today: "Today", timelineEmpty: "No runs today. Hand off a task or let it continue.", learned: "I remembered", next: "Next",
  changeTime: "Change time", taskPlaceholder: "Hand it a task…", send: "Hand off", overview: "Overview", routines: "Routines", memory: "Explicit memory",
  history: "Run history", attention: "Attention", name: "Name", mission: "Long-term mission", workspace: "Workspace", scope: "Scope", scopeGlobal: "Global", scopeWorkspace: "Project workspace", save: "Save", pause: "Pause", resume: "Wake",
  workspaceFreezeHint: "Queued runs keep their frozen workspace. New runs use the updated path after saving.", partialWarning: "Some assistant data couldn't be read. Healthy assistants are still available.", viewDetails: "View details", diagnosticTitle: "Read diagnostics",
  routineTitle: "Routine name", routinePrompt: "What to do on each run", frequency: "Run frequency", manual: "Manual only", interval: "Fixed interval", daily: "Daily",
  weekly: "Weekly", hour: "hours", at: "Time", timezone: "Timezone", runNow: "Run now", enabled: "Enabled", memoryKind: "Memory type",
  memoryBody: "What should it remember explicitly?", addMemory: "Add memory", charter: "Charter", facts: "Facts", strategy: "Strategy", openLoops: "Open loops", metrics: "Metrics",
  noMemory: "No explicit memory yet. The assistant won't treat guesses as facts.", noHistory: "No run history yet.", noAttention: "Nothing needs your attention.",
  approve: "Approve", continueRun: "Continue run", reject: "Reject", answer: "Answer", answerPlaceholder: "Enter a clear answer for the assistant…", confirmRetry: "Confirm retry", markSucceeded: "Mark succeeded", markFailed: "Mark failed", cancel: "Cancel", retryRun: "Retry", rerun: "Run again", waitingRetry: "The system will retry on schedule, or you can cancel this run.", handleAttention: "Review", changeProject: "Change project", cancelOldRun: "Cancel old run", rebindWarning: "This run froze the previous project path. Save the new path, then run again; approving this run would still use the old path.", stopRun: "Stop", openSession: "Open session", createTitle: "Create an ongoing assistant",
  createBody: "Give it a clear mission, then choose how often it should wake up.", create: "Create assistant", createName: "e.g. Code project assistant",
  createMission: "e.g. Track project health and ask before publishing when ready.", error: "That didn't work. Please retry.", saved: "Saved", resolveNote: "Resolved from Desktop", rejectNote: "The user declined to answer",
};

const zhTW: typeof zh = { ...zh, entry: "助理", newAssistant: "新增助理", memory: "明確記憶", history: "執行記錄", attention: "待處理", save: "儲存" };

export type AssistantCopy = typeof zh;

export function assistantCopy(locale: Locale): AssistantCopy {
  if (locale === "en") return en;
  if (locale === "zh-TW") return zhTW;
  return zh;
}
